name: Update lawsuits from spreadsheet

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '5 * * * *'
    
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install Node dependencies
      run: npm install
    - name: Run scripts
      run: npm run data:sheets
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git pull origin $GITHUB_REF
        git add static/data/*.json data/*.json
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push